package com.doocker.crm.po;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_desc
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String classDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_period
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private Integer classPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_feescale
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private Integer classFeescale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_before
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String classBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_after
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String classAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_resaon
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String classResaon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_by
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String classBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_id
     *
     * @param classId the value for class.class_id
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_name
     *
     * @return the value of class.class_name
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_name
     *
     * @param className the value for class.class_name
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_desc
     *
     * @return the value of class.class_desc
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassDesc() {
        return classDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_desc
     *
     * @param classDesc the value for class.class_desc
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassDesc(String classDesc) {
        this.classDesc = classDesc == null ? null : classDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_period
     *
     * @return the value of class.class_period
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public Integer getClassPeriod() {
        return classPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_period
     *
     * @param classPeriod the value for class.class_period
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassPeriod(Integer classPeriod) {
        this.classPeriod = classPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_feescale
     *
     * @return the value of class.class_feescale
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public Integer getClassFeescale() {
        return classFeescale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_feescale
     *
     * @param classFeescale the value for class.class_feescale
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassFeescale(Integer classFeescale) {
        this.classFeescale = classFeescale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_before
     *
     * @return the value of class.class_before
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassBefore() {
        return classBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_before
     *
     * @param classBefore the value for class.class_before
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassBefore(String classBefore) {
        this.classBefore = classBefore == null ? null : classBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_after
     *
     * @return the value of class.class_after
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassAfter() {
        return classAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_after
     *
     * @param classAfter the value for class.class_after
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassAfter(String classAfter) {
        this.classAfter = classAfter == null ? null : classAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_resaon
     *
     * @return the value of class.class_resaon
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassResaon() {
        return classResaon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_resaon
     *
     * @param classResaon the value for class.class_resaon
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassResaon(String classResaon) {
        this.classResaon = classResaon == null ? null : classResaon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_by
     *
     * @return the value of class.class_by
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getClassBy() {
        return classBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_by
     *
     * @param classBy the value for class.class_by
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setClassBy(String classBy) {
        this.classBy = classBy == null ? null : classBy.trim();
    }
}