package com.doocker.crm.po;

import java.util.ArrayList;
import java.util.List;

public class ClazzchangeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public ClazzchangeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUpdownIsNull() {
            addCriterion("updown is null");
            return (Criteria) this;
        }

        public Criteria andUpdownIsNotNull() {
            addCriterion("updown is not null");
            return (Criteria) this;
        }

        public Criteria andUpdownEqualTo(String value) {
            addCriterion("updown =", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownNotEqualTo(String value) {
            addCriterion("updown <>", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownGreaterThan(String value) {
            addCriterion("updown >", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownGreaterThanOrEqualTo(String value) {
            addCriterion("updown >=", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownLessThan(String value) {
            addCriterion("updown <", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownLessThanOrEqualTo(String value) {
            addCriterion("updown <=", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownLike(String value) {
            addCriterion("updown like", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownNotLike(String value) {
            addCriterion("updown not like", value, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownIn(List<String> values) {
            addCriterion("updown in", values, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownNotIn(List<String> values) {
            addCriterion("updown not in", values, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownBetween(String value1, String value2) {
            addCriterion("updown between", value1, value2, "updown");
            return (Criteria) this;
        }

        public Criteria andUpdownNotBetween(String value1, String value2) {
            addCriterion("updown not between", value1, value2, "updown");
            return (Criteria) this;
        }

        public Criteria andCbeforeIsNull() {
            addCriterion("cbefore is null");
            return (Criteria) this;
        }

        public Criteria andCbeforeIsNotNull() {
            addCriterion("cbefore is not null");
            return (Criteria) this;
        }

        public Criteria andCbeforeEqualTo(String value) {
            addCriterion("cbefore =", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeNotEqualTo(String value) {
            addCriterion("cbefore <>", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeGreaterThan(String value) {
            addCriterion("cbefore >", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeGreaterThanOrEqualTo(String value) {
            addCriterion("cbefore >=", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeLessThan(String value) {
            addCriterion("cbefore <", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeLessThanOrEqualTo(String value) {
            addCriterion("cbefore <=", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeLike(String value) {
            addCriterion("cbefore like", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeNotLike(String value) {
            addCriterion("cbefore not like", value, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeIn(List<String> values) {
            addCriterion("cbefore in", values, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeNotIn(List<String> values) {
            addCriterion("cbefore not in", values, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeBetween(String value1, String value2) {
            addCriterion("cbefore between", value1, value2, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCbeforeNotBetween(String value1, String value2) {
            addCriterion("cbefore not between", value1, value2, "cbefore");
            return (Criteria) this;
        }

        public Criteria andCafterIsNull() {
            addCriterion("cafter is null");
            return (Criteria) this;
        }

        public Criteria andCafterIsNotNull() {
            addCriterion("cafter is not null");
            return (Criteria) this;
        }

        public Criteria andCafterEqualTo(String value) {
            addCriterion("cafter =", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterNotEqualTo(String value) {
            addCriterion("cafter <>", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterGreaterThan(String value) {
            addCriterion("cafter >", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterGreaterThanOrEqualTo(String value) {
            addCriterion("cafter >=", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterLessThan(String value) {
            addCriterion("cafter <", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterLessThanOrEqualTo(String value) {
            addCriterion("cafter <=", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterLike(String value) {
            addCriterion("cafter like", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterNotLike(String value) {
            addCriterion("cafter not like", value, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterIn(List<String> values) {
            addCriterion("cafter in", values, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterNotIn(List<String> values) {
            addCriterion("cafter not in", values, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterBetween(String value1, String value2) {
            addCriterion("cafter between", value1, value2, "cafter");
            return (Criteria) this;
        }

        public Criteria andCafterNotBetween(String value1, String value2) {
            addCriterion("cafter not between", value1, value2, "cafter");
            return (Criteria) this;
        }

        public Criteria andBywhoIsNull() {
            addCriterion("bywho is null");
            return (Criteria) this;
        }

        public Criteria andBywhoIsNotNull() {
            addCriterion("bywho is not null");
            return (Criteria) this;
        }

        public Criteria andBywhoEqualTo(String value) {
            addCriterion("bywho =", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoNotEqualTo(String value) {
            addCriterion("bywho <>", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoGreaterThan(String value) {
            addCriterion("bywho >", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoGreaterThanOrEqualTo(String value) {
            addCriterion("bywho >=", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoLessThan(String value) {
            addCriterion("bywho <", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoLessThanOrEqualTo(String value) {
            addCriterion("bywho <=", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoLike(String value) {
            addCriterion("bywho like", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoNotLike(String value) {
            addCriterion("bywho not like", value, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoIn(List<String> values) {
            addCriterion("bywho in", values, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoNotIn(List<String> values) {
            addCriterion("bywho not in", values, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoBetween(String value1, String value2) {
            addCriterion("bywho between", value1, value2, "bywho");
            return (Criteria) this;
        }

        public Criteria andBywhoNotBetween(String value1, String value2) {
            addCriterion("bywho not between", value1, value2, "bywho");
            return (Criteria) this;
        }

        public Criteria andBytimeIsNull() {
            addCriterion("bytime is null");
            return (Criteria) this;
        }

        public Criteria andBytimeIsNotNull() {
            addCriterion("bytime is not null");
            return (Criteria) this;
        }

        public Criteria andBytimeEqualTo(String value) {
            addCriterion("bytime =", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeNotEqualTo(String value) {
            addCriterion("bytime <>", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeGreaterThan(String value) {
            addCriterion("bytime >", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeGreaterThanOrEqualTo(String value) {
            addCriterion("bytime >=", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeLessThan(String value) {
            addCriterion("bytime <", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeLessThanOrEqualTo(String value) {
            addCriterion("bytime <=", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeLike(String value) {
            addCriterion("bytime like", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeNotLike(String value) {
            addCriterion("bytime not like", value, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeIn(List<String> values) {
            addCriterion("bytime in", values, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeNotIn(List<String> values) {
            addCriterion("bytime not in", values, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeBetween(String value1, String value2) {
            addCriterion("bytime between", value1, value2, "bytime");
            return (Criteria) this;
        }

        public Criteria andBytimeNotBetween(String value1, String value2) {
            addCriterion("bytime not between", value1, value2, "bytime");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazzchange
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 27 23:53:50 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}