package com.doocker.crm.po;

import java.util.Date;

public class Clazzchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.updown
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String updown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.cbefore
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String cbefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.cafter
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String cafter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String bywho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.bytime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Date bytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazzchange.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.id
     *
     * @return the value of clazzchange.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.id
     *
     * @param id the value for clazzchange.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.updown
     *
     * @return the value of clazzchange.updown
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getUpdown() {
        return updown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.updown
     *
     * @param updown the value for clazzchange.updown
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setUpdown(String updown) {
        this.updown = updown == null ? null : updown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.cbefore
     *
     * @return the value of clazzchange.cbefore
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getCbefore() {
        return cbefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.cbefore
     *
     * @param cbefore the value for clazzchange.cbefore
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setCbefore(String cbefore) {
        this.cbefore = cbefore == null ? null : cbefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.cafter
     *
     * @return the value of clazzchange.cafter
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getCafter() {
        return cafter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.cafter
     *
     * @param cafter the value for clazzchange.cafter
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setCafter(String cafter) {
        this.cafter = cafter == null ? null : cafter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.bywho
     *
     * @return the value of clazzchange.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getBywho() {
        return bywho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.bywho
     *
     * @param bywho the value for clazzchange.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setBywho(String bywho) {
        this.bywho = bywho == null ? null : bywho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.bytime
     *
     * @return the value of clazzchange.bytime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Date getBytime() {
        return bytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.bytime
     *
     * @param bytime the value for clazzchange.bytime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setBytime(Date bytime) {
        this.bytime = bytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazzchange.student_id
     *
     * @return the value of clazzchange.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazzchange.student_id
     *
     * @param studentId the value for clazzchange.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}