package com.doocker.crm.po;

import java.util.Date;

public class Job extends JobKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_company
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String jobCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_station
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private String jobStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_time
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private Date jobTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.sal
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    private Float sal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_company
     *
     * @return the value of job.job_company
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getJobCompany() {
        return jobCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_company
     *
     * @param jobCompany the value for job.job_company
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setJobCompany(String jobCompany) {
        this.jobCompany = jobCompany == null ? null : jobCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_station
     *
     * @return the value of job.job_station
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public String getJobStation() {
        return jobStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_station
     *
     * @param jobStation the value for job.job_station
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setJobStation(String jobStation) {
        this.jobStation = jobStation == null ? null : jobStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_time
     *
     * @return the value of job.job_time
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public Date getJobTime() {
        return jobTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_time
     *
     * @param jobTime the value for job.job_time
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setJobTime(Date jobTime) {
        this.jobTime = jobTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.sal
     *
     * @return the value of job.sal
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public Float getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.sal
     *
     * @param sal the value for job.sal
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    public void setSal(Float sal) {
        this.sal = sal;
    }
}