package com.doocker.crm.po;

public class JobKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.student_id
     *
     * @return the value of job.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.student_id
     *
     * @param studentId the value for job.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}