package com.doocker.crm.po;

import java.util.Date;

public class Jobz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.id
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.student_name
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.qq
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.tel
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.clazz
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.company
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.jtime
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private Date jtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.station
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobz.sal
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    private double sal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.id
     *
     * @return the value of jobz.id
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.id
     *
     * @param id the value for jobz.id
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.student_name
     *
     * @return the value of jobz.student_name
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.student_name
     *
     * @param studentName the value for jobz.student_name
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.qq
     *
     * @return the value of jobz.qq
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.qq
     *
     * @param qq the value for jobz.qq
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.tel
     *
     * @return the value of jobz.tel
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.tel
     *
     * @param tel the value for jobz.tel
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.clazz
     *
     * @return the value of jobz.clazz
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.clazz
     *
     * @param clazz the value for jobz.clazz
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.company
     *
     * @return the value of jobz.company
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.company
     *
     * @param company the value for jobz.company
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.jtime
     *
     * @return the value of jobz.jtime
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public Date getJtime() {
        return jtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.jtime
     *
     * @param jtime the value for jobz.jtime
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setJtime(Date jtime) {
        this.jtime = jtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.station
     *
     * @return the value of jobz.station
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.station
     *
     * @param station the value for jobz.station
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobz.sal
     *
     * @return the value of jobz.sal
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobz.sal
     *
     * @param sal the value for jobz.sal
     *
     * @mbggenerated Wed Jul 26 19:17:52 CST 2017
     */
    public void setSal(double sal) {
        this.sal = sal;
    }
}