package com.doocker.crm.po;

import java.util.Date;

public class Lose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.loseclazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String loseclazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.losetime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Date losetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String bywho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.bmoney
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Double bmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose.reason
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.id
     *
     * @return the value of lose.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.id
     *
     * @param id the value for lose.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.loseclazz
     *
     * @return the value of lose.loseclazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getLoseclazz() {
        return loseclazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.loseclazz
     *
     * @param loseclazz the value for lose.loseclazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setLoseclazz(String loseclazz) {
        this.loseclazz = loseclazz == null ? null : loseclazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.losetime
     *
     * @return the value of lose.losetime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Date getLosetime() {
        return losetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.losetime
     *
     * @param losetime the value for lose.losetime
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setLosetime(Date losetime) {
        this.losetime = losetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.bywho
     *
     * @return the value of lose.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getBywho() {
        return bywho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.bywho
     *
     * @param bywho the value for lose.bywho
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setBywho(String bywho) {
        this.bywho = bywho == null ? null : bywho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.bmoney
     *
     * @return the value of lose.bmoney
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Double getBmoney() {
        return bmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.bmoney
     *
     * @param bmoney the value for lose.bmoney
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setBmoney(Double bmoney) {
        this.bmoney = bmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.student_id
     *
     * @return the value of lose.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.student_id
     *
     * @param studentId the value for lose.student_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose.reason
     *
     * @return the value of lose.reason
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose.reason
     *
     * @param reason the value for lose.reason
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}