package com.doocker.crm.po;

import java.util.Date;

public class Studentupdown {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.category
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.operate
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Date operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String classbefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.classafter
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String classafter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String bywho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentupdown.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.id
     *
     * @return the value of studentupdown.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.id
     *
     * @param id the value for studentupdown.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.category
     *
     * @return the value of studentupdown.category
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.category
     *
     * @param category the value for studentupdown.category
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.operate
     *
     * @return the value of studentupdown.operate
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Date getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.operate
     *
     * @param operate the value for studentupdown.operate
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setOperate(Date operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.classbefore
     *
     * @return the value of studentupdown.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getClassbefore() {
        return classbefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.classbefore
     *
     * @param classbefore the value for studentupdown.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setClassbefore(String classbefore) {
        this.classbefore = classbefore == null ? null : classbefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.classafter
     *
     * @return the value of studentupdown.classafter
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getClassafter() {
        return classafter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.classafter
     *
     * @param classafter the value for studentupdown.classafter
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setClassafter(String classafter) {
        this.classafter = classafter == null ? null : classafter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.bywho
     *
     * @return the value of studentupdown.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getBywho() {
        return bywho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.bywho
     *
     * @param bywho the value for studentupdown.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setBywho(String bywho) {
        this.bywho = bywho == null ? null : bywho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentupdown.name
     *
     * @return the value of studentupdown.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentupdown.name
     *
     * @param name the value for studentupdown.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}