package com.doocker.crm.po;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_qq
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String studentQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_tel
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String studentTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_class
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String studentClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_entry
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Date studentEntry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_cost
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Float studentCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_status
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String studentStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_qq
     *
     * @return the value of student.student_qq
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getStudentQq() {
        return studentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_qq
     *
     * @param studentQq the value for student.student_qq
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentQq(String studentQq) {
        this.studentQq = studentQq == null ? null : studentQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_tel
     *
     * @return the value of student.student_tel
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getStudentTel() {
        return studentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_tel
     *
     * @param studentTel the value for student.student_tel
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentTel(String studentTel) {
        this.studentTel = studentTel == null ? null : studentTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_class
     *
     * @return the value of student.student_class
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_class
     *
     * @param studentClass the value for student.student_class
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_entry
     *
     * @return the value of student.student_entry
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Date getStudentEntry() {
        return studentEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_entry
     *
     * @param studentEntry the value for student.student_entry
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentEntry(Date studentEntry) {
        this.studentEntry = studentEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_cost
     *
     * @return the value of student.student_cost
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Float getStudentCost() {
        return studentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_cost
     *
     * @param studentCost the value for student.student_cost
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentCost(Float studentCost) {
        this.studentCost = studentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_status
     *
     * @return the value of student.student_status
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getStudentStatus() {
        return studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_status
     *
     * @param studentStatus the value for student.student_status
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setStudentStatus(String studentStatus) {
        this.studentStatus = studentStatus == null ? null : studentStatus.trim();
    }
}