package com.doocker.crm.po;

import java.util.Date;

public class Studentlose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String classbefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.reason
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.losetime
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Date losetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String bywho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.refund
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private String refund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlose.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    private Integer name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.id
     *
     * @return the value of studentlose.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.id
     *
     * @param id the value for studentlose.id
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.classbefore
     *
     * @return the value of studentlose.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getClassbefore() {
        return classbefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.classbefore
     *
     * @param classbefore the value for studentlose.classbefore
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setClassbefore(String classbefore) {
        this.classbefore = classbefore == null ? null : classbefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.reason
     *
     * @return the value of studentlose.reason
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.reason
     *
     * @param reason the value for studentlose.reason
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.losetime
     *
     * @return the value of studentlose.losetime
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Date getLosetime() {
        return losetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.losetime
     *
     * @param losetime the value for studentlose.losetime
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setLosetime(Date losetime) {
        this.losetime = losetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.bywho
     *
     * @return the value of studentlose.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getBywho() {
        return bywho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.bywho
     *
     * @param bywho the value for studentlose.bywho
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setBywho(String bywho) {
        this.bywho = bywho == null ? null : bywho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.refund
     *
     * @return the value of studentlose.refund
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public String getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.refund
     *
     * @param refund the value for studentlose.refund
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setRefund(String refund) {
        this.refund = refund == null ? null : refund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlose.name
     *
     * @return the value of studentlose.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlose.name
     *
     * @param name the value for studentlose.name
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    public void setName(Integer name) {
        this.name = name;
    }
}