package com.doocker.crm.po;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.pay
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Double pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tel
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.statu
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer statu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazz_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.lose_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Integer loseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.entry
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    private Date entry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazz
     *
     * @return the value of student.clazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazz
     *
     * @param clazz the value for student.clazz
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.pay
     *
     * @return the value of student.pay
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Double getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.pay
     *
     * @param pay the value for student.pay
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setPay(Double pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tel
     *
     * @return the value of student.tel
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tel
     *
     * @param tel the value for student.tel
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.statu
     *
     * @return the value of student.statu
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.statu
     *
     * @param statu the value for student.statu
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazz_id
     *
     * @return the value of student.clazz_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazz_id
     *
     * @param clazzId the value for student.clazz_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.lose_id
     *
     * @return the value of student.lose_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Integer getLoseId() {
        return loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.lose_id
     *
     * @param loseId the value for student.lose_id
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setLoseId(Integer loseId) {
        this.loseId = loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.entry
     *
     * @return the value of student.entry
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public Date getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.entry
     *
     * @param entry the value for student.entry
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    public void setEntry(Date entry) {
        this.entry = entry;
    }
}