package com.doocker.crm.mapper;

import com.doocker.crm.po.Clazzchange;
import com.doocker.crm.po.ClazzchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClazzchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int countByExample(ClazzchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int deleteByExample(ClazzchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int insert(Clazzchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int insertSelective(Clazzchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    List<Clazzchange> selectByExample(ClazzchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    Clazzchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") Clazzchange record, @Param("example") ClazzchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int updateByExample(@Param("record") Clazzchange record, @Param("example") ClazzchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int updateByPrimaryKeySelective(Clazzchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazzchange
     *
     * @mbggenerated Thu Jul 27 23:53:50 CST 2017
     */
    int updateByPrimaryKey(Clazzchange record);
}