package com.doocker.crm.mapper;

import com.doocker.crm.po.Job;
import com.doocker.crm.po.JobExample;
import com.doocker.crm.po.JobKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int deleteByPrimaryKey(JobKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    Job selectByPrimaryKey(JobKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Tue Jul 25 17:40:39 CST 2017
     */
    int updateByPrimaryKey(Job record);
}