package com.doocker.crm.mapper;

import com.doocker.crm.po.Studentupdown;
import com.doocker.crm.po.StudentupdownExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentupdownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int countByExample(StudentupdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int deleteByExample(StudentupdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int insert(Studentupdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int insertSelective(Studentupdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    List<Studentupdown> selectByExample(StudentupdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    Studentupdown selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Studentupdown record, @Param("example") StudentupdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByExample(@Param("record") Studentupdown record, @Param("example") StudentupdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByPrimaryKeySelective(Studentupdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentupdown
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByPrimaryKey(Studentupdown record);
}