package com.doocker.crm.mapper;

import com.doocker.crm.po.Studentlose;
import com.doocker.crm.po.StudentloseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentloseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int countByExample(StudentloseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int deleteByExample(StudentloseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int insert(Studentlose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int insertSelective(Studentlose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    List<Studentlose> selectByExample(StudentloseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    Studentlose selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Studentlose record, @Param("example") StudentloseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByExample(@Param("record") Studentlose record, @Param("example") StudentloseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByPrimaryKeySelective(Studentlose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlose
     *
     * @mbggenerated Tue Jul 25 22:00:49 CST 2017
     */
    int updateByPrimaryKey(Studentlose record);
}